### ISSUE TITLE
Bezüge ohne erkärvideo

### ISSUE THREAD

**Issue by hhasenbalg** [MI-HSHarz/waddle#27]

**Comment by Der-Flip** [comment]
Was genau soll ich jetzt machen?

**Comment by hhasenbalg** [comment]
Das wollte ich dir grad erklären :D

Also gestern war das Treffen mit Ziemer und er hat das mit den Bezügen nicht so ganz verstanden oder es hat für ihn wenig Sinn ergeben.

Der Plan ist nun folgender. Es gibt die 4 Bezüge
zu jedem Bezug gibt es im Regelfall  5 Videos. zum einen das erklärende video und 4 Videos jeweils zu den Standorten. Also alle Videos die es zu dem entsprechenden Bezug bei dem Standort gibt einfach hintereinander,

Er meinte das es so mehr sinn ergeben würde oder besser das arbeiten mit den Videos abbildet.

Grüße 
Hagen

**Comment by Der-Flip** [comment]
Also Bezug a) bekommt die animation und anschließend alle clips zu diesem Bezug aus allen Standorten jedoch ohne die animation?
Sprich du brauchst von mir die Animationen Solo plus zusätzlich alle Bezüge abschnitte isoliert in einzelnen clips.?

**Comment by hhasenbalg** [comment]
Ich bin mir grade nicht sicher ob wir das gleich meinen also hier das Beispiel für kategorial-indentitaetsstiftend
hier wären es folgende videos:
- Animation
- Ein Video zu Stendal mit beiden Einzelvideos hintereinander
- ein Video Bad Godesber
- ein Video Weißenfels 
- Montabauer mit den beiden Videos hintereinander

die letzten 4 jeweils ohne animation

**Comment by Der-Flip** [comment]
Ah okay. Jo. Geh klar... Denk nur dran, bei einem Bezug gab nur 1 Video an nur einem Standort ;)
